FROM rust:1.65

ENV LOG_LEVEL debug

RUN apt update && \
  apt install -y \
  gcc musl-dev musl-tools protobuf-compiler

RUN cargo install cargo-watch

WORKDIR /gilgamesh
COPY . .

CMD ["cargo", "watch", "-x", "run"]
